-- MySQL Script generated by MySQL Workbench
-- Thu Dec 16 23:14:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kavaseb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kavaseb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kavaseb` DEFAULT CHARACTER SET utf8 ;
USE `kavaseb` ;

-- -----------------------------------------------------
-- Table `kavaseb`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`utilisateur` (
  `utilisateurId` INT NOT NULL AUTO_INCREMENT,
  `utilisateurNom` VARCHAR(255) NOT NULL,
  `utilisateurPrenom` VARCHAR(255) NOT NULL,
  `utilisateurMail` VARCHAR(255) NOT NULL,
  `utilisateurPseudo` VARCHAR(255) NOT NULL,
  `utilisateurMdp` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`utilisateurId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`personnalite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`personnalite` (
  `personnaliteId` INT NOT NULL AUTO_INCREMENT,
  `personnaliteNom` VARCHAR(255) NOT NULL,
  `personnalitePrenom` VARCHAR(255) NOT NULL,
  `personnaliteGenre` ENUM('M', 'F') NOT NULL,
  `personnaliteMetier` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`personnaliteId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`realisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`realisateur` (
  `realisateurId` INT NOT NULL AUTO_INCREMENT,
  `personnalite_personnaliteId` INT NOT NULL,
  PRIMARY KEY (`realisateurId`),
  INDEX `fk_realisateur_personnalite_idx` (`personnalite_personnaliteId` ASC),
  CONSTRAINT `fk_realisateur_personnalite`
    FOREIGN KEY (`personnalite_personnaliteId`)
    REFERENCES `kavaseb`.`personnalite` (`personnaliteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`scenariste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`scenariste` (
  `scenaristeId` INT NOT NULL AUTO_INCREMENT,
  `personnalite_personnaliteId` INT NOT NULL,
  PRIMARY KEY (`scenaristeId`),
  INDEX `fk_scenariste_personnalite1_idx` (`personnalite_personnaliteId` ASC),
  CONSTRAINT `fk_scenariste_personnalite1`
    FOREIGN KEY (`personnalite_personnaliteId`)
    REFERENCES `kavaseb`.`personnalite` (`personnaliteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`producteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`producteur` (
  `producteurId` INT NOT NULL AUTO_INCREMENT,
  `personnalite_personnaliteId` INT NOT NULL,
  PRIMARY KEY (`producteurId`),
  INDEX `fk_producteur_personnalite1_idx` (`personnalite_personnaliteId` ASC),
  CONSTRAINT `fk_producteur_personnalite1`
    FOREIGN KEY (`personnalite_personnaliteId`)
    REFERENCES `kavaseb`.`personnalite` (`personnaliteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`compositeur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`compositeur` (
  `compositeurId` INT NOT NULL AUTO_INCREMENT,
  `personnalite_personnaliteId` INT NOT NULL,
  PRIMARY KEY (`compositeurId`),
  INDEX `fk_compositeur_personnalite1_idx` (`personnalite_personnaliteId` ASC),
  CONSTRAINT `fk_compositeur_personnalite1`
    FOREIGN KEY (`personnalite_personnaliteId`)
    REFERENCES `kavaseb`.`personnalite` (`personnaliteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`acteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`acteur` (
  `acteurId` INT NOT NULL AUTO_INCREMENT,
  `personnalite_personnaliteId` INT NOT NULL,
  PRIMARY KEY (`acteurId`),
  INDEX `fk_acteur_personnalite1_idx` (`personnalite_personnaliteId` ASC),
  CONSTRAINT `fk_acteur_personnalite1`
    FOREIGN KEY (`personnalite_personnaliteId`)
    REFERENCES `kavaseb`.`personnalite` (`personnaliteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`doubleur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`doubleur` (
  `doubleurId` INT NOT NULL AUTO_INCREMENT,
  `personnalite_personnaliteId` INT NOT NULL,
  PRIMARY KEY (`doubleurId`),
  INDEX `fk_doubleur_personnalite1_idx` (`personnalite_personnaliteId` ASC),
  CONSTRAINT `fk_doubleur_personnalite1`
    FOREIGN KEY (`personnalite_personnaliteId`)
    REFERENCES `kavaseb`.`personnalite` (`personnaliteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`film` (
  `filmId` INT NOT NULL AUTO_INCREMENT,
  `filmTitreFR` VARCHAR(255) NOT NULL,
  `filmTitreSoustitreFR` VARCHAR(255) NOT NULL,
  `filmTitreOR` VARCHAR(255) NOT NULL,
  `filmTitreSoustitreOR` VARCHAR(255) NOT NULL,
  `scenariste_scenaristeId` INT NOT NULL,
  `realisateur_realisateurId` INT NOT NULL,
  `producteur_producteurId` INT NOT NULL,
  `acteur_acteurId` INT NOT NULL,
  `compositeur_compositeurId` INT NOT NULL,
  `filmAnnee` YEAR(4) NOT NULL,
  `filmDuree` VARCHAR(255) NOT NULL,
  `filmFormat` VARCHAR(255) NOT NULL,
  `filmAdultes` TINYINT NOT NULL,
  `filmEnfants` TINYINT NOT NULL,
  `filmAdos` TINYINT NOT NULL,
  `filmNote` INT NOT NULL,
  `filmNotequalite` INT NOT NULL,
  `filmDescription` VARCHAR(255) NOT NULL,
  `filmAvis` VARCHAR(255) NOT NULL,
  `doubleur_doubleurId` INT NOT NULL,
  PRIMARY KEY (`filmId`),
  INDEX `fk_film_realisateur1_idx` (`realisateur_realisateurId` ASC),
  INDEX `fk_film_scenariste1_idx` (`scenariste_scenaristeId` ASC),
  INDEX `fk_film_producteur1_idx` (`producteur_producteurId` ASC),
  INDEX `fk_film_compositeur1_idx` (`compositeur_compositeurId` ASC),
  INDEX `fk_film_acteur1_idx` (`acteur_acteurId` ASC),
  INDEX `fk_film_doubleur1_idx` (`doubleur_doubleurId` ASC),
  CONSTRAINT `fk_film_realisateur1`
    FOREIGN KEY (`realisateur_realisateurId`)
    REFERENCES `kavaseb`.`realisateur` (`realisateurId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_film_scenariste1`
    FOREIGN KEY (`scenariste_scenaristeId`)
    REFERENCES `kavaseb`.`scenariste` (`scenaristeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_film_producteur1`
    FOREIGN KEY (`producteur_producteurId`)
    REFERENCES `kavaseb`.`producteur` (`producteurId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_film_compositeur1`
    FOREIGN KEY (`compositeur_compositeurId`)
    REFERENCES `kavaseb`.`compositeur` (`compositeurId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_film_acteur1`
    FOREIGN KEY (`acteur_acteurId`)
    REFERENCES `kavaseb`.`acteur` (`acteurId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_film_doubleur1`
    FOREIGN KEY (`doubleur_doubleurId`)
    REFERENCES `kavaseb`.`doubleur` (`doubleurId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`editeurOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`editeurOR` (
  `editeurORId` INT NOT NULL AUTO_INCREMENT,
  `editeurORNom` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`editeurORId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`auteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`auteur` (
  `auteurId` INT NOT NULL AUTO_INCREMENT,
  `personnalite_personnaliteId` INT NOT NULL,
  PRIMARY KEY (`auteurId`),
  INDEX `fk_auteur_personnalite1_idx` (`personnalite_personnaliteId` ASC),
  CONSTRAINT `fk_auteur_personnalite1`
    FOREIGN KEY (`personnalite_personnaliteId`)
    REFERENCES `kavaseb`.`personnalite` (`personnaliteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`traducteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`traducteur` (
  `traducteurId` INT NOT NULL AUTO_INCREMENT,
  `personnalite_personnaliteId` INT NOT NULL,
  PRIMARY KEY (`traducteurId`),
  INDEX `fk_traducteur_personnalite1_idx` (`personnalite_personnaliteId` ASC),
  CONSTRAINT `fk_traducteur_personnalite1`
    FOREIGN KEY (`personnalite_personnaliteId`)
    REFERENCES `kavaseb`.`personnalite` (`personnaliteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`editeurFR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`editeurFR` (
  `editeurFRId` INT NOT NULL AUTO_INCREMENT,
  `editeurNom` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`editeurFRId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`livre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`livre` (
  `livreId` INT NOT NULL AUTO_INCREMENT,
  `livreTitreFR` VARCHAR(255) NOT NULL,
  `livreTitreSoustitreFR` VARCHAR(255) NOT NULL,
  `livreTitreOR` VARCHAR(255) NOT NULL,
  `livreTitreSoustitreOR` VARCHAR(255) NOT NULL,
  `auteur_auteurId` INT NOT NULL,
  `editeurFR_EditeurFRId` INT NOT NULL,
  `editeurOR_editeurORId` INT NOT NULL,
  `traducteur_traducteurId` INT NOT NULL,
  `livreNbrPages` INT NOT NULL,
  `livreAnnee` YEAR(4) NOT NULL,
  `livreISBN` VARCHAR(255) NOT NULL,
  `livreNote` INT NOT NULL,
  `livreNotequalite` INT NOT NULL,
  `livreDescription` VARCHAR(255) NOT NULL,
  `livreAvis` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`livreId`),
  INDEX `fk_livre_editeurOR1_idx` (`editeurOR_editeurORId` ASC),
  INDEX `fk_livre_auteur1_idx` (`auteur_auteurId` ASC),
  INDEX `fk_livre_traducteur1_idx` (`traducteur_traducteurId` ASC),
  INDEX `fk_livre_EditeurFR1_idx` (`editeurFR_EditeurFRId` ASC),
  CONSTRAINT `fk_livre_editeurOR1`
    FOREIGN KEY (`editeurOR_editeurORId`)
    REFERENCES `kavaseb`.`editeurOR` (`editeurORId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livre_auteur1`
    FOREIGN KEY (`auteur_auteurId`)
    REFERENCES `kavaseb`.`auteur` (`auteurId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livre_traducteur1`
    FOREIGN KEY (`traducteur_traducteurId`)
    REFERENCES `kavaseb`.`traducteur` (`traducteurId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livre_EditeurFR1`
    FOREIGN KEY (`editeurFR_EditeurFRId`)
    REFERENCES `kavaseb`.`editeurFR` (`editeurFRId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`studiojeu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`studiojeu` (
  `studiojeuId` INT NOT NULL AUTO_INCREMENT,
  `studiojeuNom` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`studiojeuId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`developpement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`developpement` (
  `developpementId` INT NOT NULL AUTO_INCREMENT,
  `studiojeu_studiojeuId` INT NOT NULL,
  PRIMARY KEY (`developpementId`),
  INDEX `fk_developpementjeu_studiojeu1_idx` (`studiojeu_studiojeuId` ASC),
  CONSTRAINT `fk_developpementjeu_studiojeu1`
    FOREIGN KEY (`studiojeu_studiojeuId`)
    REFERENCES `kavaseb`.`studiojeu` (`studiojeuId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`editeur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`editeur` (
  `editeurId` INT NOT NULL AUTO_INCREMENT,
  `studiojeu_studiojeuId` INT NOT NULL,
  PRIMARY KEY (`editeurId`),
  INDEX `fk_productionjeu_studiojeu1_idx` (`studiojeu_studiojeuId` ASC),
  CONSTRAINT `fk_productionjeu_studiojeu1`
    FOREIGN KEY (`studiojeu_studiojeuId`)
    REFERENCES `kavaseb`.`studiojeu` (`studiojeuId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`jeu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`jeu` (
  `jeuId` INT NOT NULL AUTO_INCREMENT,
  `jeuTitreFR` VARCHAR(255) NOT NULL,
  `jeuTitreSoustitreFR` VARCHAR(255) NOT NULL,
  `jeuTitreOR` VARCHAR(255) NOT NULL,
  `jeuTitreSoustitreOR` VARCHAR(255) NOT NULL,
  `developpement_developpementId` INT NOT NULL,
  `editeur_editeurId` INT NOT NULL,
  `doubleur_doubleurId` INT NOT NULL,
  `compositeur_compositeurId` INT NOT NULL,
  `jeuAnnee` YEAR(4) NOT NULL,
  `jeuNombreJoueurs` INT NOT NULL,
  `jeuNote` INT NOT NULL,
  `jeuDescription` VARCHAR(255) NOT NULL,
  `jeuAvis` VARCHAR(255) NOT NULL,
  `scenariste_scenaristeId` INT NOT NULL,
  `acteur_acteurId` INT NOT NULL,
  PRIMARY KEY (`jeuId`),
  INDEX `fk_jeu_developpement1_idx` (`developpement_developpementId` ASC),
  INDEX `fk_jeu_editeur1_idx` (`editeur_editeurId` ASC),
  INDEX `fk_jeu_compositeur1_idx` (`compositeur_compositeurId` ASC),
  INDEX `fk_jeu_scenariste1_idx` (`scenariste_scenaristeId` ASC),
  INDEX `fk_jeu_acteur1_idx` (`acteur_acteurId` ASC),
  INDEX `fk_jeu_doubleur1_idx` (`doubleur_doubleurId` ASC),
  CONSTRAINT `fk_jeu_developpement1`
    FOREIGN KEY (`developpement_developpementId`)
    REFERENCES `kavaseb`.`developpement` (`developpementId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jeu_editeur1`
    FOREIGN KEY (`editeur_editeurId`)
    REFERENCES `kavaseb`.`editeur` (`editeurId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jeu_compositeur1`
    FOREIGN KEY (`compositeur_compositeurId`)
    REFERENCES `kavaseb`.`compositeur` (`compositeurId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jeu_scenariste1`
    FOREIGN KEY (`scenariste_scenaristeId`)
    REFERENCES `kavaseb`.`scenariste` (`scenaristeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jeu_acteur1`
    FOREIGN KEY (`acteur_acteurId`)
    REFERENCES `kavaseb`.`acteur` (`acteurId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jeu_doubleur1`
    FOREIGN KEY (`doubleur_doubleurId`)
    REFERENCES `kavaseb`.`doubleur` (`doubleurId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`genre` (
  `genreId` INT NOT NULL AUTO_INCREMENT,
  `genreNom` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`genreId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`langue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`langue` (
  `langueId` INT NOT NULL AUTO_INCREMENT,
  `langueNom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`langueId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`systeme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`systeme` (
  `systemeId` INT NOT NULL AUTO_INCREMENT,
  `systemeNom` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`systemeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`systeme_jeu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`systeme_jeu` (
  `jeu_jeuId` INT NOT NULL,
  `systeme_systemeId` INT NOT NULL,
  PRIMARY KEY (`jeu_jeuId`, `systeme_systemeId`),
  INDEX `fk_jeu_has_systeme_systeme1_idx` (`systeme_systemeId` ASC),
  INDEX `fk_jeu_has_systeme_jeu1_idx` (`jeu_jeuId` ASC),
  CONSTRAINT `fk_jeu_has_systeme_jeu1`
    FOREIGN KEY (`jeu_jeuId`)
    REFERENCES `kavaseb`.`jeu` (`jeuId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jeu_has_systeme_systeme1`
    FOREIGN KEY (`systeme_systemeId`)
    REFERENCES `kavaseb`.`systeme` (`systemeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`serie` (
  `serieId` INT NOT NULL AUTO_INCREMENT,
  `serieTitreFR` VARCHAR(255) NOT NULL,
  `serieTitreSoustitreFR` VARCHAR(255) NOT NULL,
  `serieTitreOR` VARCHAR(255) NOT NULL,
  `serieTitreSoustitreOR` VARCHAR(255) NOT NULL,
  `scenariste_scenaristeId` INT NOT NULL,
  `realisateur_realisateurId` INT NOT NULL,
  `producteur_producteurId` INT NOT NULL,
  `acteur_acteurId` INT NOT NULL,
  `compositeur_compositeurId` INT NOT NULL,
  `serieAnnee` YEAR(4) NOT NULL,
  `serieDuree` VARCHAR(255) NOT NULL,
  `serieFormat` VARCHAR(255) NOT NULL,
  `serieAdultes` TINYINT NOT NULL,
  `serieEnfants` TINYINT NOT NULL,
  `serieAdos` TINYINT NOT NULL,
  `serieNote` INT NOT NULL,
  `serieNotequalite` INT NOT NULL,
  `serieDescription` VARCHAR(255) NOT NULL,
  `serieAvis` VARCHAR(255) NOT NULL,
  `doubleur_doubleurId` INT NOT NULL,
  PRIMARY KEY (`serieId`),
  INDEX `fk_serie_realisateur1_idx` (`realisateur_realisateurId` ASC),
  INDEX `fk_serie_compositeur1_idx` (`compositeur_compositeurId` ASC),
  INDEX `fk_serie_producteur1_idx` (`producteur_producteurId` ASC),
  INDEX `fk_serie_scenariste1_idx` (`scenariste_scenaristeId` ASC),
  INDEX `fk_serie_acteur1_idx` (`acteur_acteurId` ASC),
  INDEX `fk_serie_doubleur1_idx` (`doubleur_doubleurId` ASC),
  CONSTRAINT `fk_serie_realisateur1`
    FOREIGN KEY (`realisateur_realisateurId`)
    REFERENCES `kavaseb`.`realisateur` (`realisateurId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_serie_compositeur1`
    FOREIGN KEY (`compositeur_compositeurId`)
    REFERENCES `kavaseb`.`compositeur` (`compositeurId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_serie_producteur1`
    FOREIGN KEY (`producteur_producteurId`)
    REFERENCES `kavaseb`.`producteur` (`producteurId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_serie_scenariste1`
    FOREIGN KEY (`scenariste_scenaristeId`)
    REFERENCES `kavaseb`.`scenariste` (`scenaristeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_serie_acteur1`
    FOREIGN KEY (`acteur_acteurId`)
    REFERENCES `kavaseb`.`acteur` (`acteurId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_serie_doubleur1`
    FOREIGN KEY (`doubleur_doubleurId`)
    REFERENCES `kavaseb`.`doubleur` (`doubleurId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`livreGenre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`livreGenre` (
  `livre_livreId` INT NOT NULL,
  `genre_genreId` INT NOT NULL,
  PRIMARY KEY (`livre_livreId`, `genre_genreId`),
  INDEX `fk_livre_has_genre_genre1_idx` (`genre_genreId` ASC),
  INDEX `fk_livre_has_genre_livre1_idx` (`livre_livreId` ASC),
  CONSTRAINT `fk_livre_has_genre_livre1`
    FOREIGN KEY (`livre_livreId`)
    REFERENCES `kavaseb`.`livre` (`livreId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livre_has_genre_genre1`
    FOREIGN KEY (`genre_genreId`)
    REFERENCES `kavaseb`.`genre` (`genreId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`filmLangue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`filmLangue` (
  `film_filmId` INT NOT NULL,
  `langue_langueId` INT NOT NULL,
  PRIMARY KEY (`film_filmId`, `langue_langueId`),
  INDEX `fk_film_has_langue_langue1_idx` (`langue_langueId` ASC),
  INDEX `fk_film_has_langue_film1_idx` (`film_filmId` ASC),
  CONSTRAINT `fk_film_has_langue_film1`
    FOREIGN KEY (`film_filmId`)
    REFERENCES `kavaseb`.`film` (`filmId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_film_has_langue_langue1`
    FOREIGN KEY (`langue_langueId`)
    REFERENCES `kavaseb`.`langue` (`langueId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`serieLangue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`serieLangue` (
  `serie_serieId` INT NOT NULL,
  `langue_langueId` INT NOT NULL,
  PRIMARY KEY (`serie_serieId`, `langue_langueId`),
  INDEX `fk_serie_has_langue_langue1_idx` (`langue_langueId` ASC),
  INDEX `fk_serie_has_langue_serie1_idx` (`serie_serieId` ASC),
  CONSTRAINT `fk_serie_has_langue_serie1`
    FOREIGN KEY (`serie_serieId`)
    REFERENCES `kavaseb`.`serie` (`serieId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_serie_has_langue_langue1`
    FOREIGN KEY (`langue_langueId`)
    REFERENCES `kavaseb`.`langue` (`langueId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`livreLangue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`livreLangue` (
  `livre_livreId` INT NOT NULL,
  `langue_langueId` INT NOT NULL,
  PRIMARY KEY (`livre_livreId`, `langue_langueId`),
  INDEX `fk_livre_has_langue_langue1_idx` (`langue_langueId` ASC),
  INDEX `fk_livre_has_langue_livre1_idx` (`livre_livreId` ASC),
  CONSTRAINT `fk_livre_has_langue_livre1`
    FOREIGN KEY (`livre_livreId`)
    REFERENCES `kavaseb`.`livre` (`livreId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livre_has_langue_langue1`
    FOREIGN KEY (`langue_langueId`)
    REFERENCES `kavaseb`.`langue` (`langueId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kavaseb`.`filmGenre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kavaseb`.`filmGenre` (
  `film_filmId` INT NOT NULL,
  `genre_genreId` INT NOT NULL,
  PRIMARY KEY (`film_filmId`, `genre_genreId`),
  INDEX `fk_film_has_genre_genre1_idx` (`genre_genreId` ASC),
  INDEX `fk_film_has_genre_film1_idx` (`film_filmId` ASC),
  CONSTRAINT `fk_film_has_genre_film1`
    FOREIGN KEY (`film_filmId`)
    REFERENCES `kavaseb`.`film` (`filmId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_film_has_genre_genre1`
    FOREIGN KEY (`genre_genreId`)
    REFERENCES `kavaseb`.`genre` (`genreId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
